<a href="https://colab.research.google.com/github/tkach3nkoo/MN/blob/main/%D0%9B%D0%A01_%D0%A2%D0%BA%D0%B0%D1%87%D0%B5%D0%BD%D0%BA%D0%BE%2C_%D0%B3%D1%80%D1%83%D0%BF%D0%B0_9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
print(np.__version__)


2.1.3


In [2]:
a = np.array([2, 4, 6, 8, 10])
print(a)
print(type(a))


[ 2  4  6  8 10]
<class 'numpy.ndarray'>


In [3]:
zeros = np.zeros(10)
ones = np.ones(8)
sevens = np.full(6, 7)

print(zeros)
print(ones)
print(sevens)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1.]
[7 7 7 7 7 7]


In [4]:
a = np.arange(1, 21)
even = np.arange(2, 21, 2)

print(a)
print(even)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 2  4  6  8 10 12 14 16 18 20]


In [5]:
a = np.linspace(0, 1, 11)
print(a)


[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [6]:
a = np.arange(1, 13)
matrix = a.reshape(3, 4)
print(matrix)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [7]:
print(matrix.ndim)
print(matrix.shape)
print(matrix.size)
print(matrix.dtype)


2
(3, 4)
12
int64


In [8]:
a = np.array([1.2, 3.5, 5.7, 7.9])
b = a.astype(int)

print(b)


[1 3 5 7]


In [9]:
a = np.array([10, 20, 30, 40, 50, 60, 70, 80])

print(a[0])
print(a[-1])
print(a[2:6])
print(a[::2])


10
80
[30 40 50 60]
[10 30 50 70]


In [10]:
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

print(a[1, 2])
print(a[1])
print(a[:, 2])
print(a[1:, :2])


7
[5 6 7 8]
[ 3  7 11]
[[ 5  6]
 [ 9 10]]


In [11]:
a = np.arange(1, 16)
a[5:10] = 0
print(a)


[ 1  2  3  4  5  0  0  0  0  0 11 12 13 14 15]


In [12]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])

print(a + b)
print(a - b)
print(a * b)
print(a / b)


[11 22 33 44 55]
[ -9 -18 -27 -36 -45]
[ 10  40  90 160 250]
[0.1 0.1 0.1 0.1 0.1]


In [13]:
a = np.array([4, 8, 15, 16, 23, 42])

print("Сума:", np.sum(a))
print("Середнє:", np.mean(a))
print("Мінімум:", np.min(a))
print("Максимум:", np.max(a))
print("Медіана:", np.median(a))
print("Стандартне відхилення:", np.std(a))


Сума: 108
Середнє: 18.0
Мінімум: 4
Максимум: 42
Медіана: 15.5
Стандартне відхилення: 12.315302134607444


In [14]:
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print("Сума всіх:", np.sum(a))
print("Сума по стовпцях:", np.sum(a, axis=0))
print("Сума по рядках:", np.sum(a, axis=1))
print("Середнє по стовпцях:", np.mean(a, axis=0))


Сума всіх: 45
Сума по стовпцях: [12 15 18]
Сума по рядках: [ 6 15 24]
Середнє по стовпцях: [4. 5. 6.]


In [15]:
a = np.arange(1, 11)

print("Квадрати:", np.square(a))
print("Корені:", np.sqrt(a))
print("Логарифми:", np.log(a))


Квадрати: [  1   4   9  16  25  36  49  64  81 100]
Корені: [1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766]
Логарифми: [0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458 2.30258509]


In [16]:
a = np.array([3, 7, 12, 18, 21, 25, 30, 34])

print(a[a > 15])
print(a[a % 2 == 0])
print(a[(a >= 10) & (a <= 30)])


[18 21 25 30 34]
[12 18 30 34]
[12 18 21 25 30]


In [17]:
a = np.array([-5, 3, -2, 8, -1, 10, 0])
a[a < 0] = 0
print(a)


[ 0  3  0  8  0 10  0]


In [18]:
np.random.seed(42)
a = np.random.randint(0, 101, 20)

print(a)
print("Більше 50:", np.sum(a > 50))
print("Менше або дорівнює 50:", np.sum(a <= 50))


[51 92 14 71 60 20 82 86 74 74 87 99 23  2 21 52  1 87 29 37]
Більше 50: 12
Менше або дорівнює 50: 8


In [19]:
a = np.arange(1, 25)

m1 = a.reshape(4, 6)
m2 = a.reshape(6, 4)
m3 = a.reshape(2, 3, 4)

print(m1.shape)
print(m2.shape)
print(m3.shape)


(4, 6)
(6, 4)
(2, 3, 4)


In [20]:
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

print("Вертикально:")
print(np.vstack((A, B)))

print("Горизонтально:")
print(np.hstack((A, B)))


Вертикально:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Горизонтально:
[[1 2 5 6]
 [3 4 7 8]]


In [21]:
a = np.arange(1, 13).reshape(3, 4)

b = a.flatten()
c = a.ravel()

print(b)
print(c)
print(np.array_equal(b, c))


[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
True


In [22]:
a = np.array([2, 4, 6])
b = np.array([1, 3, 5])

print("Сума:", a + b)
print("Різниця:", a - b)
print("a * 3:", a * 3)
print("b * 3:", b * 3)


Сума: [ 3  7 11]
Різниця: [1 1 1]
a * 3: [ 6 12 18]
b * 3: [ 3  9 15]


In [23]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(np.dot(a, b))
print(a @ b)


32
32


In [24]:
v = np.array([3, 4])

norm = np.linalg.norm(v)
v_normalized = v / norm

print("Норма:", norm)
print("Нормалізований вектор:", v_normalized)


Норма: 5.0
Нормалізований вектор: [0.6 0.8]


In [25]:
a = np.array([1, 0, 0])
b = np.array([0, 1, 0])

print(np.cross(a, b))


[0 0 1]


In [26]:
a = np.array([1, 2])
b = np.array([2, 1])

cos_angle = np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))
angle = np.degrees(np.arccos(cos_angle))

print("Косинус:", cos_angle)
print("Кут:", angle)


Косинус: 0.7999999999999998
Кут: 36.86989764584404


In [27]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

print(A.T)
print(np.transpose(A))


[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]


In [29]:
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[2, 0],
              [1, 2]])

print("Поелементний добуток:")
print(A * B)

print("Матричний добуток:")
print(A @ B)




Поелементний добуток:
[[2 0]
 [3 8]]
Матричний добуток:
[[ 4  4]
 [10  8]]


In [30]:
A = np.array([[4, 7],
              [2, 6]])

det = np.linalg.det(A)
inv = np.linalg.inv(A)

print("Визначник:", det)
print("Обернена матриця:")
print(inv)
print("Перевірка:")
print(A @ inv)


Визначник: 10.000000000000002
Обернена матриця:
[[ 0.6 -0.7]
 [-0.2  0.4]]
Перевірка:
[[ 1.00000000e+00 -1.11022302e-16]
 [ 1.11022302e-16  1.00000000e+00]]


In [31]:
A = np.array([[2, 1],
              [1, 3]])
b = np.array([5, 6])

x = np.linalg.solve(A, b)
print(x)


[1.8 1.4]


In [32]:
I = np.eye(4)
A = np.arange(1, 17).reshape(4, 4)

result = A @ I

print(I)
print(result)
print(np.allclose(A, result))


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]
True


In [33]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print(A + 10)


[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [35]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

v = np.array([10, 20, 30])

print(A + v)



[[11 22 33]
 [14 25 36]
 [17 28 39]]


In [36]:
A = np.array([[10, 20, 30],
              [20, 30, 40],
              [30, 40, 50]])

mean = np.mean(A, axis=0)
std = np.std(A, axis=0)
Z = (A - mean) / std

print(Z)


[[-1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487]]


In [37]:
np.random.seed(42)

a = np.random.randint(1, 101, 10)
b = np.random.random((3, 3))
c = np.random.normal(size=1000)

print(a)
print(b)
print("Середнє:", np.mean(c))
print("Стандартне відхилення:", np.std(c))


[52 93 15 72 61 21 83 87 75 75]
[[0.86617615 0.60111501 0.70807258]
 [0.02058449 0.96990985 0.83244264]
 [0.21233911 0.18182497 0.18340451]]
Середнє: 0.02216865975826456
Стандартне відхилення: 0.9792284455184356


In [38]:
grades = np.random.randint(0, 101, 30)

print(grades)
print("Середня оцінка:", np.mean(grades))
print("Медіана:", np.median(grades))
print("Найвища:", np.max(grades))
print("Найнижча:", np.min(grades))
print("Не менше 60:", np.sum(grades >= 60))
print("Не менше 90, %:", np.mean(grades >= 90) * 100)


[25  2 40 59 13 74 81 11 86 11 12 24 44 18 54 99 44  7 92 52 54 31 50 43
 81 69 17 82 21 36]
Середня оцінка: 44.4
Медіана: 43.5
Найвища: 99
Найнижча: 2
Не менше 60: 8
Не менше 90, %: 6.666666666666667


In [39]:
sales = np.array([[120, 150, 170, 160],
                  [80, 90, 100, 110],
                  [200, 180, 210, 230]])

product_totals = np.sum(sales, axis=1)
month_totals = np.sum(sales, axis=0)

print("Продажі товарів:", product_totals)
print("Продажі по місяцях:", month_totals)
print("Найкращий товар:", np.argmax(product_totals) + 1)
print("Найкращий місяць:", np.argmax(month_totals) + 1)
print("Середні продажі товарів:", np.mean(sales, axis=1))


Продажі товарів: [600 380 820]
Продажі по місяцях: [400 420 480 500]
Найкращий товар: 3
Найкращий місяць: 4
Середні продажі товарів: [150.  95. 205.]


In [40]:
A = np.random.randint(1, 21, (5, 5))
print(A)

print("Головна діагональ:", np.trace(A))
print("Побічна діагональ:", np.trace(np.fliplr(A)))
print("Максимум по рядках:", np.max(A, axis=1))
print("Мінімум по стовпцях:", np.min(A, axis=0))

mean = np.mean(A)
B = A.copy()
B[B < mean] = 0

print("Середнє:", mean)
print(B)


[[ 9  3 10 19  3]
 [15  1  7 12 17]
 [20  5  4 12 20]
 [18 17 19  9  4]
 [ 2  4  2 15  2]]
Головна діагональ: 25
Побічна діагональ: 38
Максимум по рядках: [19 17 20 19 15]
Мінімум по стовпцях: [2 1 2 9 2]
Середнє: 9.96
[[ 0  0 10 19  0]
 [15  0  0 12 17]
 [20  0  0 12 20]
 [18 17 19  0  0]
 [ 0  0  0 15  0]]


In [41]:
X = np.array([[2, 4, 6],
              [1, 3, 5],
              [5, 7, 9]])

print("1-2:", np.linalg.norm(X[0] - X[1]))
print("1-3:", np.linalg.norm(X[0] - X[2]))
print("2-3:", np.linalg.norm(X[1] - X[2]))


1-2: 1.7320508075688772
1-3: 5.196152422706632
2-3: 6.928203230275509


In [42]:
A = np.array([[1, 2, 3, 4],
              [2, 3, 4, 5],
              [3, 4, 5, 6],
              [4, 5, 6, 7]], dtype=float)

norms = np.linalg.norm(A, axis=1)
B = A / norms[:, np.newaxis]

print("Норми:", norms)
print(B)


Норми: [ 5.47722558  7.34846923  9.2736185  11.22497216]
[[0.18257419 0.36514837 0.54772256 0.73029674]
 [0.27216553 0.40824829 0.54433105 0.68041382]
 [0.32349832 0.43133109 0.53916387 0.64699664]
 [0.35634832 0.4454354  0.53452248 0.62360956]]


In [43]:
A = np.array([[1, 2, 1],
              [2, 1, -1],
              [3, -1, 2]])

b = np.array([9, 8, 3])

x = np.linalg.solve(A, b)
check = A @ x

print("Розв'язок:", x)
print("Перевірка:", check)
print("b:", b)
print(np.allclose(check, b))


Розв'язок: [ 2.22222222  3.44444444 -0.11111111]
Перевірка: [9. 8. 3.]
b: [9 8 3]
True
